name: Update Media URLs

on:
  schedule:
    - cron: '0 9 * * *'  # 毎日9:00 UTC (18:00 JST)
  workflow_dispatch:  # 手動実行も可能

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        pip install requests python-dotenv
        
    - name: Set up Node.js for Wrangler
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Wrangler
      run: npm install -g wrangler
      
    - name: Run update script
      run: python update_media_urls.py
      env:
        INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
        
    - name: Upload to Cloudflare KV
      run: |
        wrangler kv:key put --namespace-id=${{ secrets.CLOUDFLARE_KV_NAMESPACE_ID }} cafe_data_kv.json --path=cafe_data_kv.json
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add cafe_data_kv.json instagram_posts.json
        git diff --staged --quiet || git commit -m "Update media URLs - $(date '+%Y-%m-%d %H:%M:%S')"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}